package com.sdapps.formula1fy.core.models

object F1Contants {
    const val RED_BULL = "red_bull"
    const val MERCEDES = "mercedes"
    const val FERRARI = "ferrari"
    const val ALPINE = "alpine"
    const val MCLAREN = "mclaren"
    const val ALFA_ROMEO = "alfa"
    const val HAAS = "haas"
    const val ALPHATAURI = "alphatauri"
    const val ASTON_MARTIN = "aston_martin"
    const val WILLIAMS = "williams"

    /*DRIVERS*/
    const val ALBON = "albon"
    const val LATIFI = "latifi"
    const val RICCIARDO = "ricciardo"
    const val LECLERC = "leclerc"
    const val SAINZ = "sainz"
    const val HAMILTON = "hamilton"
    const val RUSSELL = "russell"
    const val ALONSO = "alonso"
    const val OCON = "ocon"
    const val ZHOU = "zhou"
    const val BOTTAS = "bottas"
    const val KMAG = "kevin_magnussen"
    const val SCHUMACHER = "mick_schumacher"
    const val NORRIS = "norris"
    const val GASLY = "gasly"
    const val TSUNODA = "tsunoda"
    const val VETTEL = "vettel"
    const val VERSTAPPEN = "max_verstappen"
    const val PEREZ = "perez"
    const val STROLL = "stroll"
    const val NICK_DE_VRIES = "de_vries"
    const val HULKENBERG = "hulkenberg"
}